<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Version>1.4.0.2</Version>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="Configuration\configPage.html" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Configuration\configPage.html" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Jellyfin.Plugin.YoutubeMetadata.UnitTests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Jellyfin.Controller" Version="10.11.0" />
    <PackageReference Include="Jellyfin.Data" Version="10.11.0" />
    <PackageReference Include="Microsoft.Extensions.FileSystemGlobbing" Version="9.0.10" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="9.0.10" />
    <PackageReference Include="NYoutubeDLP" Version="0.13.2" />
    <PackageReference Include="System.IO.Abstractions" Version="22.0.16" />
  </ItemGroup>

  <ItemGroup>
    <None Update="meta.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  
  <Target Name="Zip" AfterTargets="PostBuildEvent">
    <ItemGroup>
      <FilesToDelete Include="$(BaseOutputPath)/$(Configuration)/Jellyfin.YoutubeMetadata*.zip" />
      <TempZipDirectory Include="$(OutputPath)output" />
    </ItemGroup>
    <Delete Files="@(FilesToDelete)" />
    <Copy SourceFiles="$(OutputPath)$(AssemblyName).dll" DestinationFolder="@(TempZipDirectory)" />
    <Copy SourceFiles="$(OutputPath)NYoutubeDLP.dll" DestinationFolder="@(TempZipDirectory)" />
    <Copy SourceFiles="$(OutputPath)Newtonsoft.Json.dll" DestinationFolder="@(TempZipDirectory)" />
    <Copy SourceFiles="$(OutputPath)System.IO.Abstractions.dll" DestinationFolder="@(TempZipDirectory)" />
    <Copy SourceFiles="$(OutputPath)TestableIO.System.IO.Abstractions.dll" DestinationFolder="@(TempZipDirectory)" />
    <Copy SourceFiles="$(OutputPath)Testably.Abstractions.FileSystem.Interface.dll" DestinationFolder="@(TempZipDirectory)" />
    <Copy SourceFiles="$(OutputPath)TestableIO.System.IO.Abstractions.Wrappers.dll" DestinationFolder="@(TempZipDirectory)" />
    <Copy SourceFiles="$(OutputPath)\meta.json" DestinationFolder="@(TempZipDirectory)" />
    <ZipDirectory SourceDirectory="@(TempZipDirectory)" DestinationFile="$(BaseOutputPath)/$(Configuration)/Jellyfin.YoutubeMetadata@v$(Version).zip" />
    <RemoveDir Directories="@(TempZipDirectory)" />
  </Target>
</Project>
